### ISSUE TITLE
Does this work on Android

### ISSUE THREAD

**Issue by jamesrcounts** [approvals/ApprovalTests.Java#11]
I have a coworker who want's to know if this works with Android?  

If it does then maybe we should add it to the README

**Comment by bmurmistro** [comment]
Anyone?

**Comment by onstottj** [comment]
I could be wrong, but unit tests would only be running on your development machine.  You could make the approval tests library available to only the unit tests (using 'test' scope in maven, etc...), so this seems feasible.
