### ISSUE TITLE
Using custom approval namers and writers with CombinationApprovals

### ISSUE THREAD

**Issue by JCook21** [approvals/ApprovalTests.Java#158]
Thanks for the great work on this library, it's a fantastic tool. I have a use case where I need to use custom approval namers and writers. This is very doable using standard Approvals but it doesn't seem to be possible with CombinationApprovals. Have I missed something and is this actually possible? If not, would you consider adding this as an enhancement? I'd be happy to work on this as an enhancement if this is something that you would like to see added.

**Comment by JCook21** [comment]
@LarsEckart sorry that I couldn't make it today but I would love to make a future meeting. Is this a regular, every Monday meeting? If not, when is the next one?

**Comment by LarsEckart** [comment]
No worries, it actually didn't happen, I also had to cancel. Yes, we aim to meet next Monday at that time again.

**Comment by JCook21** [comment]
Sounds good, I'll try to make it then!

**Comment by LarsEckart** [comment]
@JCook21 send me an email lars.eckart@gmail.com and I'll add you to the event invites :)

**Comment by LarsEckart** [comment]
Give 11.6.0 a try and let us know if it's what you needed :)

**Comment by JCook21** [comment]
Thanks for your help on this @LarsEckart and @isidore. I should have some time to play around with the new release next week and I'll get back to you then. :)

**Comment by JCook21** [comment]
@LarsEckart sorry about the delay in looking into this. I finally got some time recently and there's a nasty dependency clash between a dep of recent versions of ApprovalTests and our project. I'm trying to work around this and I'll let you know what I manage to do.
