### ISSUE TITLE
Combination approvals stores outputs of all parameters in a single file

### ISSUE THREAD

**Issue by ragunathjawahar** [approvals/ApprovalTests.Java#167]
I have the following use case,
- A need to verify different SVG files that vary by parameter.
- Output of each parameter needs to be saved into its own file (important, because I could use the IDE to preview how they look like)

Right now, 
1. Combination approvals prepends parameter information to each output (this breaks the IDE's preview feature).
2. Output for each execution is written to the same file (again, breaks the IDE's preview feature)

Can we,
1. Write the result of each test into its own file? (the parameters can become a part of the file name?)
2. If (1) is accomplished, I can use the scrubber to remove parameter from the output.

**Comment by ragunathjawahar** [comment]
🤔 for simpler cases, parameterized tests with a custom namer would suffice.

**Comment by LarsEckart** [comment]
resolved, use NamerFactory.withParameters.
