### ISSUE TITLE
Add Araxis Merge support for Mac OS/X

### ISSUE THREAD

**Issue by talios** [approvals/ApprovalTests.Java#172]
Araxis Merge is available on OS/X via:

```
/Applications/Araxis Merge.app/Contents/Utilities/compare
```

as documented at https://www.araxis.com/merge/documentation-os-x/command-line.en

**Comment by LarsEckart** [comment]
hello and thank you for your contribution.

We'll take this in [next Monday](https://www.worldtimebuddy.com/?qm=1&lid=588409,2193733,5454711&h=588409&date=2021-8-2&sln=22-24&hf=1) when we get together again.
If you want to join, let me know your email address and I send you an invite :)

**Comment by talios** [comment]
@LarsEckart - Any chance this will ever get implemented?

**Comment by isidore** [comment]
can you join us the monday 10 mst?

**Comment by LarsEckart** [comment]
Wow, from 2021, I'm sorry that we forgot about this issue, thank you for not giving up on us and askign again. The reporter will be in the next release, again "next Monday", as in, tomorrow!

In the meantime, might be worth mentioning that ApprovalTests strives to be customizable without us requiring new releases. Maybe that's exactly how you solved it in the meantime, but if not, let me share you [this link](https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/how_to/CreateCustomReporter.md) and the example how I now [implemented](https://github.com/LarsEckart/bootstrap/blob/araxis-reporter/src/test/java/kata/AraxisReporter.java) it in my starter project without it being part of Approvaltests.

And ofc, if you can make it, join us tomorrow evening for a brief moment, it's always nice to meet users of Approvaltests and get feedback.

**Comment by talios** [comment]
@LarsEckart Cheers! I only noticed it as I was reinstalling Araxis on a new machine to check out the new release, and also noticed I'd locked our Approvals version back to a few releases.
