### ISSUE TITLE
Pairwise test outcome depends on execution order

### ISSUE THREAD

**Issue by rzabini** [approvals/ApprovalTests.Java#175]
Pairwise tests rely on a random variable to generate the subset of permutations. This variable is defined as [static in the Case class](https://github.com/approvals/ApprovalTests.Java/blob/da4aeead6c51e1dd070e9db2b19a241d5f7b7cc2/approvaltests/src/main/java/org/approvaltests/combinations/pairwise/Case.java#L16-L20).

So the random value(s) obtained by test methods in `PairwiseTest` class depend on the execution order of these methods, and if one of them is added/removed, altering the order, the set of values in the _received_ file may be different from the set in the  _approved_ file. For instance, commenting out the `testPairs` method, the `testPairsScrubbed` fails.

I think that the issue may be solved by making non-static the `random` variable (and the corresponding method).

**Comment by LarsEckart** [comment]
thank you!

Fixed in 12.0.1 which is being released right now.
