### ISSUE TITLE
Test failures in concurrent execution

### ISSUE THREAD

**Issue by rzabini** [approvals/ApprovalTests.Java#181]
JUnit has an experimental parallel test execution [feature](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution). When trying to use it in ApprovalsTests test suite, some failures occur.

Failures may be observed by adding the file `src/test/resources/junit-platform.properties` with the following items

```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default = concurrent
```
... in modules:
- approvaltests
- approvaltests-tests
- approvaltests-util-tests

**Comment by LarsEckart** [comment]
Thank you for your contribution.
