### ISSUE TITLE
Combination approval inputs have a trailing space character

### ISSUE THREAD

**Issue by ragunathjawahar** [approvals/ApprovalTests.Java#195]
During the first run of a combination approval test, the received file contains a trailing space character at the end of each result. However, when using IntelliJ's diff viewer to pass contents of the received file to the approved file, IntelliJ strips these trailing spaces. For subsequent runs, the received file does not match the approved file due to the whitespace character mismatch.

My current workaround is to avoid the IntelliJ diff viewer, delete the blank approved file and rename the received file instead. Am I missing something here or is this a bug we need to fix?

**Comment by satorstefan** [comment]
Hello Ragunathja,

I run into the same issues. I would considers this a bug.

I "fixed" it by setting the newline seperator:
https://www.jetbrains.com/help/idea/configuring-line-endings-and-line-separators.html

and by editing the .editorconfig and setting:
trim_trailing_whitespace = false

Both settings are available when the approval file is open:
![image](https://user-images.githubusercontent.com/25597168/195272290-b5c04bf6-6ed5-4c8a-8b78-8fd87c2ad237.png)

Best regards
Stefan

**Comment by ragunathjawahar** [comment]
Thank you!
