### ISSUE TITLE
Feature request: more information on failure

### ISSUE THREAD

**Issue by tomasbjerre** [approvals/ApprovalTests.Java#252]
[build-131-ubuntu-latest-8.zip](https://github.com/approvals/ApprovalTests.Java/files/8405061/build-131-ubuntu-latest-8.zip)
I have test cases that fail on `verify` even when the received and approved files are idential.

~~I am attaching the workspace as a zip-file.~~ File available here:
https://github.com/tomasbjerre/git-changelog-lib/suites/5912229860/artifacts/201754121

```
✔ ~/Hämtningar/build [master {origin/master}|✚ 31] 
17:19 $ sha256sum src/test/java/se/bjurr/gitchangelog/api/GitChangelogApiTest.testPathFilterCanBeSpecified.received.txt
d898c9bf901f7a7356d426b2333b78d14bc4cb26837dbed5050988f3a730abc6  src/test/java/se/bjurr/gitchangelog/api/GitChangelogApiTest.testPathFilterCanBeSpecified.received.txt
✔ ~/Hämtningar/build [master {origin/master}|✚ 31] 
17:19 $ sha256sum src/test/java/se/bjurr/gitchangelog/api/GitChangelogApiTest.testPathFilterCanBeSpecified.approved.txt
d898c9bf901f7a7356d426b2333b78d14bc4cb26837dbed5050988f3a730abc6  src/test/java/se/bjurr/gitchangelog/api/GitChangelogApiTest.testPathFilterCanBeSpecified.approved.txt
```

The outout I am getting is:

```
java.lang.Error: Failed Approval
  Approved:/home/runner/work/git-changelog-lib/git-changelog-lib/./src/test/java/se/bjurr/gitchangelog/api/GitChangelogApiTest.testPathFilterCanBeSpecified.approved.txt
  Received:/home/runner/work/git-changelog-lib/git-changelog-lib/./src/test/java/se/bjurr/gitchangelog/api/GitChangelogApiTest.testPathFilterCanBeSpecified.received.txt
	at org.approvaltests.approvers.FileApprover.fail(FileApprover.java:57)
	at org.approvaltests.Approvals.verify(Approvals.java:212)
	at org.approvaltests.Approvals.verify(Approvals.java:167)
	at org.approvaltests.Approvals.verify(Approvals.java:175)
	at org.approvaltests.Approvals.verify(Approvals.java:51)
	at org.approvaltests.Approvals.verify(Approvals.java:60)
	at se.bjurr.gitchangelog.test.ApprovalsWrapper.verify(ApprovalsWrapper.java:33)
	at se.bjurr.gitchangelog.api.GitChangelogApiTest.testPathFilterCanBeSpecified(GitChangelogApiTest.java:138)
```

One question is, of course, why does it fail? But I think the bigger problem here is the lack of information in the failure. I think it would save much time for many users if it said something more helpful.

**Comment by LarsEckart** [comment]
@tomasbjerre   I think you forgot to attach the workspace?! Or if you have it as a github repo, that will also do.

**Comment by tomasbjerre** [comment]
Sorry. Having some problems uploading it, but it is available here:
https://github.com/tomasbjerre/violations-lib/suites/5912760049/artifacts/201792627

**Comment by LarsEckart** [comment]
@tomasbjerre we ran `gradle test` on 2 systems (both macos) but the build succeeds for us.

**Comment by tomasbjerre** [comment]
Realized now I supplied the wrong link. Here it is:
https://github.com/tomasbjerre/git-changelog-lib/suites/5912229860/artifacts/201754121
