### ISSUE TITLE
Kaleidoscope 3 places ksdiff in `/usr/local/bin`

### ISSUE THREAD

**Issue by talios** [approvals/ApprovalTests.Java#262]
```java
 public static DiffInfo KALEIDOSCOPE       = new DiffInfo(
        "/Applications/Kaleidoscope.app/Contents/MacOS/ksdiff", TEXT_AND_IMAGE);
```

When using Kaleidoscope 3 it's no longer picked up by Approval Tests as the CLI integration is now installed into `/usr/local/bin`.

**Comment by LarsEckart** [comment]
https://github.com/approvals/ApprovalTests.Java/commit/976edf50d231b5ac5a0a8b3bf967317bf8d9ee0d

after review by @isidore I will make a new release.

**Comment by LarsEckart** [comment]
[15.4.0](https://github.com/approvals/ApprovalTests.Java/releases/tag/15.4.0) released

**Comment by talios** [comment]
Cheers!
