### ISSUE TITLE
No diff tool popup

### ISSUE THREAD

**Issue by jeanpalaz** [approvals/ApprovalTests.Java#27]
Hello,

I'm a new user of ApprovalTests in Java and Eclipse.
In video tutorial I can see a popup diff tool. But in my case I don't have this behaviour the only one is a message in console saying:
To approve run : move /Y "C:\dev\workspace_SCT\ApprovalsTesting.\src\GettingStartedWithApprovalsTest.testName.received.txt"  "C:\dev\workspace_SCT\ApprovalsTesting.\src\GettingStartedWithApprovalsTest.testName.approved.txt"

Is there a specific configuration to have this feature? I have also installed WinMerge.

Thx for helping it's look a very good tool for testing
Jean

**Comment by isidore** [comment]
[UseReporter(typeof(DiffReporter))]

Llewellyn Falco
www.approvaltests.com

**Comment by jamesrcounts** [comment]
For Java?

Sent from my Windows Phone
________________________________

**Comment by isidore** [comment]
sorry.
@UseReporter(DiffReporter.class)

Llewellyn Falco
www.approvaltests.com

**Comment by Jean31** [comment]
Thx for helping, I have tried this
```
@Test
@UseReporter(DiffReporter.class)
public void testName() throws Exception {
		Approvals.verify("Hello World!");
}
```
I run the test and still have the console wiht command line

May be is there another configuration in eclipse to do?

**Comment by isidore** [comment]
actually this is odd for a couple reasons.

1) In java the diff reporter is assumed
2) junit reporter would have caught and given a standard error message
3) Winmerge would have also caught.

Would you be able to do a skype session and let me see your environment?

Llewellyn Falco
www.approvaltests.com

**Comment by Jean31** [comment]
Thx to propose a Skype but i'm at work with an ugly/bad proxy :(
I have discovered org.approvaltests.reporters.windows and tried
@UseReporter(org.approvaltests.reporters.windows.WinMergeReporter.class)
but gave me an error
``
java.lang.RuntimeException: Unable to find WinMerge at C:\Program Files\WinMerge\WinMergeU.exe
You can install it at http://winmerge.org/
	at org.approvaltests.reporters.GenericDiffReporter.report(GenericDiffReporter.java:43)
	...
``
But my winmerge is installed in  C:\Program Files (x86)\WinMerge\WinMergeU.exe
I added C:\Program Files (x86)\WinMerge in PATH, but same error
Can I change approvel to tell him the good path?

**Comment by Jean31** [comment]
Hey the pullrequest of @martinsson #22 will soved my problem :)
Is it planned?

**Comment by mcarlson-sb** [comment]
For others who find this. I ran into a similar situation as originally reported.
@UseReporter(DiffReporter.class) seems to default to using TortoiseIDiff (installed with TortoiseSVN)
Once I installed TortoiseSVN it just worked

**Comment by boorac** [comment]
Issue is present on Linux as well. Using meld as diftool

**Comment by LarsEckart** [comment]
We'll take a look soon at PR #22 and hopefully get this resolved soon. Personally, on macos, we also ran into this issue a couple of times, the necessary changes weren't too difficult then. It's just that we don't develop usually on win/linux to properly persuade such issues.
