### ISSUE TITLE
Where to find a current release

### ISSUE THREAD

**Issue by beatngu13** [approvals/ApprovalTests.Java#30]
The last public release seems to be [v013](https://sourceforge.net/projects/approvaltests/files/ApprovalTests.Java/) (?) from 2013, which is pretty old and doesn't contain important fixes. Where can I download a current release? I also can't find anything on Maven Central.

**Comment by isidore** [comment]
yeah, I haven't been able to get it into maven central yet (something I really need to do).
The latest release is in the release tab
https://github.com/approvals/ApprovalTests.Java/releases

**Comment by beatngu13** [comment]
Great, thanks! Created a [pull request](https://github.com/approvals/ApprovalTests.Java/pull/31) to update the misleading part within the README.md.
