### ISSUE TITLE
Can it be used in a groovy file using spock framework ?

### ISSUE THREAD

**Issue by mike03081972** [approvals/ApprovalTests.Java#32]

**Comment by isidore** [comment]
no idea. try it and let me know. if it doesn't work, I'd be happy to pair with you to get it working.

**Comment by mike03081972** [comment]
It's not working

**Comment by isidore** [comment]
makes sense, I've never really used groovy or spock, but if you are up for a skype call I bet we could get it working in an hour or so. email me isidore at setgame com

**Comment by rzabini** [comment]
You may take a look at my attempt here: https://github.com/rzabini/ApprovalTests.Spock.
Adding the basic support for Spock is as easy as adding "org.spockframework.runtime.model.FeatureMetadata" to the list of annotation names in AttributeStackSelector.classNames.
However Spock generates test methods names at compile time, and these names are in the form: _$spock_feature_0_0_, _$spock_feature_0_1_, and so on. So the name of the expected txt file would be in the same useless form. To generate a meaningful name we have to look into the said _FeatureMetadata_ annotation class, and extract its _name_ (and _parameterNames_ as Spock allows to put arguments in test methods).

**Comment by LarsEckart** [comment]
I'll hope to have a look at spock 2 soon and will give it a try. If there are issues, we'll open another issue or simply add it to our todo file.
