### ISSUE TITLE
Add ApprovalTests to Maven

### ISSUE THREAD

**Issue by mwinteringham** [approvals/ApprovalTests.Java#34]
Apologies if this is something that has been raised before but I would really like to see the latest version of ApprovalTests on Maven. It's proving to be a little bit of a headache with open source projects to have half of the dependencies in Maven and then ApprovalTests needing to be imported.

Whilst it's not a difficult problem to solve it can be time consuming.

**Comment by bitcoder** [comment]
isn't it already there? although it has "com." prefix in the package name.
https://mvnrepository.com/artifact/com.approvaltests/approvaltests

**Comment by mwinteringham** [comment]
Yeah this is an old request before it was added. Will close this down.
