### ISSUE TITLE
can  I tell the framework to use x i.e. a specific directory

### ISSUE THREAD

**Issue by nagkumar** [approvals/ApprovalTests.Java#375]
I  don't wish to clutter all approved txts to be placed in source code direct.. like in below

![image](https://user-images.githubusercontent.com/332234/230812176-f221fcb2-7b16-49c3-9494-550f6c0d683e.png)

Is it possible to  define with any options to say, where to look for all the approved files location may be resources folder etc

**Comment by nagkumar** [comment]
Ideally, I may want to place all w.r.t to class location but on a custom specific directory or all in one main/java/res without any further subdirectories as per the class package name..

![image](https://user-images.githubusercontent.com/332234/230812599-e73cf4e5-4a9b-418f-ae6f-7109202cca0e.png)

**Comment by nagkumar** [comment]
or as main/java/res/aprt/approved

![image](https://user-images.githubusercontent.com/332234/230812774-f3208c6e-3842-484e-b65f-2b7430df36aa.png)

**Comment by LarsEckart** [comment]
hello,

I think what you are looking for is [Package Settings](https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/Configuration.md#package-level-settings).
Create a class called `PackageSettings` next to your tests or in root folder of your tests, or in specific package next to your tests to only apply for this package.

**Comment by nagkumar** [comment]
Thank You..

This works for me

```
package com.tejasoft.tests.ju5.aprt;

public final class PackageSettings
{
    public static String UseApprovalSubdirectory = "approved";
}

```
