### ISSUE TITLE
javax.mail replaced by jakarta.mail

### ISSUE THREAD

**Issue by ethanmills** [approvals/ApprovalTests.Java#376]
Per https://mvnrepository.com/artifact/com.sun.mail/javax.mail, `javax.mail` has moved to `jakarta.mail`. I'd be happy to raise a PR for this change if desired.

**Comment by LarsEckart** [comment]
Are you using `TestUtils.displayEmail(Message)`?

If so, would you appreciate an `EmailApprovals.verify(Message)` instead?

**Comment by ethanmills** [comment]
We're not currently using the email functionality, just looking to clean up our dependencies to remove the javax namespace
