### ISSUE TITLE
is there any option to run the approval testing to create approved files

### ISSUE THREAD

**Issue by nagkumar** [approvals/ApprovalTests.Java#402]
When we have too many approval tests, the first time or any time I want to reset approved files, is there any option for an approval test to create new baseline of files for approval i.e.

`x.approved.txt`

This way instead of running and getting received files and then renaming each received file to approved efforts can be avoided

**Comment by ScottBob** [comment]
Yes there is: try AutoApproveReporter or AutoApproveWhenEmptyReporter. If you want to set that as the reporter for your whole system, we suggest using the "[Package Level](https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/how_to/ConfigureReporters.md#method-3-package-level)" setting.
