### ISSUE TITLE
JSON Normalisation

### ISSUE THREAD

**Issue by mbechto** [approvals/ApprovalTests.Java#422]
Invoking `JsonApprovals.verifyJson()` with a JSON that is content-wise identical but structurally different (specifically, the order of keys in an object) yields a difference each time it changes.

This behaviour it is a little inconvenient, since:

- JSON as a data format does not demand keys in an object to be ordered - the order does not matter
- The issue could be fixed by implementing ordering of JSON keys in the API that is tested, but this feels to me like an anti-pattern: Namely to change the behaviour / characteristics of the implementation unnecessarily and just for the sake of testing. In fact, depending on the implementation it may be even impossible to do so

That being said, I wonder whether sorting JSON keys by default in ApprovalTests would improve the ease of use for snapshot based testing of dynamically generated JSON objects such as in REST APIs?

What is your take on that?

**Comment by mbechto** [comment]
To illustrate that, here is what our current workaround looks like:

```java
final ObjectMapper objectMapper = new ObjectMapper().enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);
final String orderedJson = objectMapper.writeValueAsString(objectMapper.readValue(jsonResponseBody, Map.class));
JsonApprovals.verifyJson(orderedJson);
```

**Comment by ScottBob** [comment]
The latest release (v21.2.0) should solve this problem for you. We disagree that reordoring is an antipattern, but we do agree that it should be easy and convenient for people to verify JSON over which they have no control of the creation.
