### ISSUE TITLE
TestUtils.displayFile(String file) fails on mac

### ISSUE THREAD

**Issue by MarioKusek** [approvals/ApprovalTests.Java#429]
On Mac `TestUtils.displayFile(String file)` internally calls in `com.spun.util.tests.LinuxOpener` method `executeOnLinux` with arguments: `file` and `"open"`.

Here is code:
https://github.com/approvals/ApprovalTests.Java/blob/87f090b02dc5df7a727bbe7efa5e81c4d8b4d78d/approvaltests-util/src/main/java/com/spun/util/tests/LinuxOpener.java#L12-L33

The problematic are following lines in `which` method:
https://github.com/approvals/ApprovalTests.Java/blob/87f090b02dc5df7a727bbe7efa5e81c4d8b4d78d/approvaltests-util/src/main/java/com/spun/util/tests/LinuxOpener.java#L25-L28

Often the `exitValue` is 141 and not `0` as expected. The reason is that `FileUtils.readStream` wants to read stream before process output stream is not ready. This is checked in `com.spun.util.io.FileUtils` in `readBuffer` method:
https://github.com/approvals/ApprovalTests.Java/blob/87f090b02dc5df7a727bbe7efa5e81c4d8b4d78d/approvaltests-util/src/main/java/com/spun/util/io/FileUtils.java#L238-L243

The `ready` method returns `false` because stream is not ready and it doesn't go into while loop. After loop it calls `close` which closes stream/pipe and when process want to write to output stream/pipe it can not. The process gets signal SIGPIPE (exit value 141) from the kernel and it ends with exit code 141. Description for SIGPIPE can be found here https://unix.stackexchange.com/a/433348

The solution is to switch lines 26 and 27 in `LinuxOpener` so we wait for process to finish and after that we read process output. Those 4 lines look like this:

```java
 Process p = Runtime.getRuntime().exec(command1); 
 p.waitFor(); 
 String output = FileUtils.readStream(p.getInputStream()).trim(); 
 int exitValue = p.exitValue(); 
```

Here is code that can reproduce error:

```java
var dir = Files.createTempDirectory(Path.of("."), "test");
var htmlFile = dir.resolve("index.html");
Files.writeString(htmlFile, """
        <html>
        <body>
        Some text
        </body>
        </html>
        """, StandardCharsets.UTF_8);

var absolutePath = htmlFile.toAbsolutePath().toString();

for(int i = 0; i < 10; i++) {
  if(correct_executeOnLinux(absolutePath, "open"))
    System.out.println("OK");
  else
    System.out.println("Can not open");
}
```

This is output:

```
OK
Can not open
Can not open
Can not open
Can not open
Can not open
Can not open
Can not open
Can not open
Can not open
```

We can see that first time it runs correctly, but other times it fails. I have checked exit code in failure and it is 141.

**Comment by LarsEckart** [comment]
Thank you for this very detailed bug report!

At the latest, Llewellyn and I can pick this up next Monday when we meet again, but perhaps @isidore can resolve this sooner. :)
