### ISSUE TITLE
verifyXml() escaping behaviour

### ISSUE THREAD

**Issue by JCook21** [approvals/ApprovalTests.Java#466]
I'm working with Jackson to generate some XML that I'd like to then approve with the `verifyXml()` method. Jackson takes care of escaping special characters in the XML but doesn't pretty print it. I'm finding some inconsistencies with how Approvals then formats the XML:

- Single quotes in the DTD are being converted to double quotes. This isn't a major issue but is a difference between what Jackson outputs and how Approvals then formats it.
- Emoji characters, which Jackson doesn't escape, are being escaped by Approvals. For example, "😼" is being output as &#128572;
- XML special characters, which Jackson has already escaped, are being escaped again. For example, Jackson outputs `&amp;` but Approvals then changes this to `&amp;amp`.

Do you have any comments on this? Is it possible to just apply formatting to the XML string that adds line breaks and indents but without further formatting the content?

**Comment by isidore** [comment]
1. would you be willing to join us on a zoom call to work on this?
2. do you have a unit test we can look at to see the issues?

**Comment by JCook21** [comment]
Happy to join you on a Zoom call to look into this. I don't have a unit test yet but I can look to add one today.

**Comment by JCook21** [comment]
I'm wondering if a similar approach to `JsonJacksonApprovals` would work here too.

**Comment by JCook21** [comment]
Added a draft pull request #473 with a couple of tests to show the discrepancies I'm seeing. Strangely, I couldn't verify that `&amp;` is being converted to `&amp;amp;`, even though I saw this in my own codebase a few weeks ago.

**Comment by LarsEckart** [comment]
hey Jeremy,

it's been a while but tonight we worked on it. It's tricky. A suggested workaround is to write this line of code:

```java
public void verifyJacksonXml(String xml) {
    Approvals.verify(prettyPrintWithJackson(xml), new Options().forFile().withExtension(".xml"));
}
```
where you have to implement the `prettyPrintWithJackson` still yourself.

We'll get back to it in a week, if you want to join us, let us know.

**Comment by LarsEckart** [comment]
hey @JCook21 

we think we fixed this by using [XOM](http://www.xom.nu/). But we also created a seam so that you can pass your own xml pretty printer that Approvals will use.

If you get it working with jackson as the pretty printer, we'd love if you'd contribute it back!  (we weren't able to when we tried) :) 

We're publishing a new release now that contains `XmlXomApprovals.verifyXml()` and `Approvals.verifyXml(xml, prettyPrinter)`
