### ISSUE TITLE
Publish maven artifact?

### ISSUE THREAD

**Issue by brockn** [approvals/ApprovalTests.Java#5]
Is there a plan to publish a maven artifact?

**Comment by martinsson** [comment]
Three years later :) I would still like to have approvals in maven. Any possibility we could work on getting #23 merged @isidore ?

**Comment by tyrcho** [comment]
> My more modern approval java port at (nikolavp/approval) is shipped to maven central already. You can view the latest version here

@nikolavp I had a look at your version, but I lack this feature from approvals: [verifyAllCombinations](https://github.com/approvals/ApprovalTests.Java/blob/master/java/org/approvaltests/combinations/CombinationApprovals.java#L30)

**Comment by isidore** [comment]
been done for a while, sorry I didn't close it.
