### ISSUE TITLE
Combination approval inputs have a trailing space character

### ISSUE THREAD

**Issue by kosletr** [approvals/ApprovalTests.Java#508]
Similar to issue https://github.com/approvals/ApprovalTests.Java/issues/195
Combination approval inputs have a trailing space character. I don't know why the issue was closed since the problem persists. I am running Intellij 2024.1 on a M1 macbook. 

<img width="868" alt="image" src="https://github.com/approvals/ApprovalTests.Java/assets/48099304/1c1b6626-36de-4d9d-83cf-25fbbfd229d8">

<img width="1526" alt="image" src="https://github.com/approvals/ApprovalTests.Java/assets/48099304/99136b9c-c798-4e75-99cb-626430c39fe1">

**Comment by kosletr** [comment]
I fixed it by changing the Intellij settings to stop removing trailing whitespaces on save. Settings -> Editor -> General -> On Save -> Uncheck "Remove trailing spaces on: "

<img width="1073" alt="image" src="https://github.com/approvals/ApprovalTests.Java/assets/48099304/90e40ca4-9210-4c53-83f1-64eca23818f7">

**Comment by rd-chichung-liu** [comment]
I had the same problem. The described workaround didn't fix it. In addition, I had to edit the .editorconfig:
trim_trailing_whitespace = false. I am running IntelliJ 2024.1.1 on an M1 Macbook.
