### ISSUE TITLE
Option to allow waiting for reporter to terminate

### ISSUE THREAD

**Issue by FWest98** [approvals/ApprovalTests.Java#517]
This would be particularly helpful for reporters such as the IntelliJ one. Consider the case where the output for 5 tests change between test runs. Then, this library will try to open IntelliJ 5 times - however, in practice the merge view will be opened once, one other command is "queued", and all other commands are ignored. So if you're not sufficiently quick, you might have approved 2 changes and the others are left on disk and require manual fixup.

Would it be possible to add a "wait" option, where the IntelliJ reporter will only return once the merge window is closed? Ideally, after closing and accepting changes, the current test should pass as well.

It would be even nicer if there was some other way to improve the integration with IntelliJ, so there can be a single overview of all failed tests where the diff can easily be opened - but I guess that is way more work.

**Comment by LarsEckart** [comment]
hello,
this is not something that we want to explore further. There is an interface, `ReporterWithApprovalPower` which might go in this direction and could be helpful if you want to look into this. While we can spawn the IntelliJ diff viewer, the event that the window is closed does not propagate back to ApprovalTests, so we cannot wait for it. The wiring to make all this work is very complicated.

If you want to look at it together or want to discuss your idea further, you can join us on zoom. We usually meet Monday evening and can forward you an invitation.

**Comment by FWest98** [comment]
Hi! With the merge of https://github.com/approvals/ApprovalTests.Java/pull/520 and having developed my own IntelliJ plugin (https://plugins.jetbrains.com/plugin/24706-approvaltests-support/edit), the usecase for this issue has been solved in another way anyway. Thanks!
