### ISSUE TITLE
`NoSuchMethod` when running ApprovalTests on Java 8

### ISSUE THREAD

**Issue by rohanKanojia** [approvals/ApprovalTests.Java#546]
Hello, we use ApprovalTests in [Fabric8 Kubernetes Client](https://github.com/fabric8io/kubernetes-client)

We wanted to merge pull request by dependabot for bumping approval tests to v24.4.0 https://github.com/fabric8io/kubernetes-client/pull/6255

However, we noticed that Approval tests are no longer running on JDK8 properly, currently we're seeing this error:

logs from [GitHub Action](https://github.com/fabric8io/kubernetes-client/actions/runs/10557195752/job/29244233770?pr=6255)
```
Error:    CRDGeneratorApprovalTest.apiV1ApprovalTest:92 » NoClassDefFound Could not initialize class org.approvaltests.reporters.DefaultFrontLoadedReporter
org.approvaltests.reporters.DefaultFrontLoadedReporter
Error:    CRDGeneratorApprovalTest.apiV2ApprovalTest:118 » NoSuchMethod java.util.Map.entry(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map$Entry;
```

[Javadoc](https://docs.oracle.com/javase/9/docs/api/java/util/Map.html#entry-K-V-) for `Map.entry(Object, Object)` says it's introduced since Java 9. However, I'm not able to find any references to this method in your codebase.

Same test completes successfully on JDK11 and JDK17.  

I wanted to check if this change was intentional in a minor release. Is support for Java8 dropped from ApprovalTests?

**Comment by LarsEckart** [comment]
I'll have a look. We still want to be compatible with jdk8, even though right now our pipelines don't use it. The eclipse code formatter maven plugin is the reason for this, as their latest versions requrie at least jdk 11 and from what it looks like, soon 21 https://code.revelc.net/formatter-maven-plugin/eclipse-versions.html

**Comment by LarsEckart** [comment]
Another finding. We bumped jakarta-servlet-api and that also has:
> Minimum Java SE Version
> Java SE 17 or higher

@isidore this is used in `approvaltests-util` in `ServletContextLoader`.

**Comment by LarsEckart** [comment]
Found another one: 
>TestNG v7.6.0 and above: JDK 11 or higher.

if we have such dependencies (even when marked optional I think), we cannot compile with jdk 8 (and find such issues)

**Comment by LarsEckart** [comment]
When I rip out all those dependencies, I can compile our project with jdk8, only aprovaltests-tests doesnt work because well, there we really started using later APIs and thos bumped the dependency on this project. 

```
[INFO] ApprovalTests.Java ................................. SUCCESS [  0.159 s]
[INFO] approvaltests-util ................................. SUCCESS [  3.117 s]
[INFO] approvaltests ...................................... SUCCESS [  1.159 s]
[INFO] approvaltests-util-tests ........................... SUCCESS [  0.117 s]
[INFO] approvaltests-tests ................................ FAILURE [  0.219 s]
```

**Comment by rohanKanojia** [comment]
@LarsEckart : Thanks for your swift response. Is it okay to say that ApprovalTests no longer support Java8?

**Comment by LarsEckart** [comment]
We'll discuss this, so far we wanted to stay jdk8 compatible and I consider this rather an unfortunate mistake. I'll get back to you if we bump the min jdk or if we verify all our dependencies to be able to stay on 8.

**Comment by LarsEckart** [comment]
Please give version `24.5.0` a try, it should work again on jdk 8.

**Comment by manusa** [comment]
> Please give version `24.5.0` a try, it should work again on jdk 8.

This is working now, thanks!

_https://github.com/fabric8io/kubernetes-client/pull/6349_
