### ISSUE TITLE
`VerifyJson` shall use the `GsonBuilder` function passed when reorder is false.

### ISSUE THREAD

**Issue by ShadyAbuKalam** [approvals/ApprovalTests.Java#551]
I have these lines
`
Function1<GsonBuilder, GsonBuilder>    gsonSerializeNull = GsonBuilder::serializeNulls;
JsonApprovals.verifyJson(jsonString, false,  gsonSerializeNull);
`

Internally JsonApprovals will call `JsonUtils.prettyPrint` that creates a new Gson object without the configuration we passed, so we still get rid of nulls, that I still want.

Some suggested possible solutions:
1. Change the prettyPrint to accept the Gson customization function.
2. Change the prettyPrint function to consider removing nulls is messing up with json. ( I prefer this one )
3. Write the PrettyPrint function inside the JsonApproval module.

-----
I am willing to do this as PR, if maintainers agree.

**Comment by LarsEckart** [comment]
Indeed, this should have been possible before.
We did option 1 and it will be part of the next release.
